# MLflow Hyperparameter Tuning

`Hyperparameter Tuning`:

- the process to **select the optimal configuration settings** for a machine learning model before the training process begins in order to **maximize its predictive accuracy**.

## Environment

In [1]:
from src.tracking import tracking_uri
import sys
from pathlib import Path

import mlflow
import torch

# data
ROOT = Path.cwd().parent
sys.path.insert(0, str(ROOT))

RAW = ROOT / "data" / "raw"
PROCESSED = ROOT / "data" / "processed"

# mlflow instance
mlflow.set_tracking_uri(tracking_uri())

# print versions and mlflow
print("torch     ", torch.__version__)
print("cuda      ", torch.cuda.is_available())
print("tracking  ", tracking_uri())
print("experiments", [e.name for e in mlflow.search_experiments()])

torch      2.13.0+cu130
cuda       False
tracking   http://mlflow:5000
experiments ['yolo-plate-detection', '/workspace/runs', 'Default']

## Split data

Define same split before sweep.

- sweep results are comparable based on the same split

In [2]:
from src.data_loader import build_split, verify_split, write_data_yaml

# limit for fast smoke run; e.g. 200
# LIMIT = None  # unlimit
LIMIT = 200  # limit 200

# random seed
SEED = 0

# print split
print(build_split(RAW, PROCESSED, val_fraction=0.2, limit=LIMIT, seed=SEED))
print(verify_split(PROCESSED))

names = (RAW / "classes.txt").read_text().split()
data_yaml = write_data_yaml(ROOT / "configs" / "data.yaml", PROCESSED, names)
print(data_yaml.read_text())

{'train': 160, 'val': 40, 'orphan_images': 0, 'orphan_labels': 0}
{'train': 160, 'val': 40}
path: /workspace/data/processed
train: train/images
val: val/images
nc: 1
names: ['car_plate']

## Define sweep (Grid search)

`Grid search`:

- Exhaustively tests every single **combination in a predefined matrix of values**.

In [3]:
import yaml

# experiment name
EXPERIMENT = "yolo-plate-detection-sweep"

# load base param config
base_cfg = yaml.safe_load((ROOT / "configs" / "train.yaml").read_text())
base_cfg["project"] = str(ROOT / base_cfg["project"])

# define grid
GRID = [{"epochs": e, "name": f"tune-ep{e}"} for e in (10, 20, 30)]

print(f"experiment {EXPERIMENT}")
for g in GRID:
    print(" ", g)

experiment yolo-plate-detection-sweep
  {'epochs': 10, 'name': 'tune-ep10'}
  {'epochs': 20, 'name': 'tune-ep20'}
  {'epochs': 30, 'name': 'tune-ep30'}

## Run sweep

- Each config in grid becomes its own mlflow run
- log with mlflow

In [4]:
from src.tracking import run_sweep

# run sweep with helper function
results = run_sweep(
    grid=GRID,
    base_cfg=base_cfg,
    data_yaml=data_yaml,
    processed_dir=PROCESSED,
    raw_dir=RAW,
    experiment=EXPERIMENT,
    run_name=lambda cfg: f"cpu-ep{cfg['epochs']}-{cfg['imgsz']}px",
)

for r in results:
    print(r)

============================================================
[1/3] cpu-ep10-416px  {'epochs': 10, 'name': 'tune-ep10'}
============================================================
Ultralytics 8.4.116 🚀 Python-3.12.13 torch-2.13.0+cu130 CPU (Intel Core 5 120U)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/workspace/configs/data.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=10, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=416, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=tune-ep10, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/workspace/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/workspace/runs/tune-ep10, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    430867  ultralytics.nn.modules.head.Detect           [1, 16, None, [64, 128, 256]]
YOLO11n summary: 182 layers, 2,590,035 parameters, 2,590,019 gradients, 6.5 GFLOPs

Transferred 448/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
WARNING ⚠️ train: Slow image access detected (ping: 4.1±1.0 ms, read: 41.9±28.4 MB/s, size: 720.9 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning /workspace/data/processed/train/labels... 160 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 160/160 324.3it/s 0.5s0.1s
train: New cache created: /workspace/data/processed/train/labels.cache
WARNING ⚠️ val: Slow image access detected (ping: 4.3±0.8 ms, read: 31.9±28.0 MB/s, size: 920.2 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /workspace/data/processed/val/labels... 40 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 40/40 327.4it/s 0.1s.8s
val: New cache created: /workspace/data/processed/val/labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to /workspace/runs/tune-ep10/labels.jpg...

2026/08/08 18:21:48 INFO mlflow.tracking.fluent: Experiment with name 'yolo-plate-detection-sweep' does not exist. Creating a new experiment.

MLflow: logging run_id(62fe34c7d0284adb83902a508fba6dde) to http://mlflow:5000
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 416 train, 416 val
Using 0 dataloader workers
Logging results to /workspace/runs/tune-ep10
Starting training for 10 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10         0G      1.105      3.404      1.024          8        416: 100% ━━━━━━━━━━━━ 20/20 3.5s/it 1:111.6sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.0s/it 3.1s2.3s
                   all         40         43    0.00317      0.884      0.325      0.177

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/10         0G      1.192      1.929      1.068          7        416: 100% ━━━━━━━━━━━━ 20/20 1.7s/it 33.5s1.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2s/it 3.6s2.7s
                   all         40         43    0.00292      0.814      0.186     0.0495

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/10         0G      1.159      1.842      1.042          8        416: 100% ━━━━━━━━━━━━ 20/20 2.0s/it 40.8s1.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.5s/it 4.5s3.1s
                   all         40         43    0.00217      0.605     0.0528     0.0416

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/10         0G      1.257      1.836      1.038          8        416: 100% ━━━━━━━━━━━━ 20/20 1.7s/it 34.3s1.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.7s1.7s
                   all         40         43    0.00989      0.279     0.0109    0.00703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/10         0G      1.123      1.612      1.021          9        416: 100% ━━━━━━━━━━━━ 20/20 1.9s/it 37.3s1.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1s/it 3.2s2.1s
                   all         40         43    0.00845      0.093    0.00699    0.00413

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/10         0G      1.102      1.526      0.978          8        416: 100% ━━━━━━━━━━━━ 20/20 1.6s/it 32.9s1.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.6s1.9s
                   all         40         43      0.414      0.256      0.256      0.168

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/10         0G       1.01       1.38     0.9543          8        416: 100% ━━━━━━━━━━━━ 20/20 1.9s/it 37.5s1.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.9s/it 5.6s3.3s
                   all         40         43      0.796      0.674      0.736      0.484

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/10         0G     0.9899      1.364     0.9785          8        416: 100% ━━━━━━━━━━━━ 20/20 1.7s/it 33.9s1.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3s/it 4.0s2.6ss
                   all         40         43      0.994      0.791      0.932      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/10         0G     0.9486      1.287     0.9258          9        416: 100% ━━━━━━━━━━━━ 20/20 1.5s/it 29.1s1.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3it/s 2.4s1.6s
                   all         40         43      0.947      0.836       0.94      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/10         0G     0.9375      1.263     0.9187          8        416: 100% ━━━━━━━━━━━━ 20/20 1.3s/it 26.4s1.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1s/it 3.2s2.1s
                   all         40         43      0.945      0.907      0.951      0.732

10 epochs completed in 0.118 hours.
Optimizer stripped from /workspace/runs/tune-ep10/weights/last.pt, 5.4MB
Optimizer stripped from /workspace/runs/tune-ep10/weights/best.pt, 5.4MB

Validating /workspace/runs/tune-ep10/weights/best.pt...
Ultralytics 8.4.116 🚀 Python-3.12.13 torch-2.13.0+cu130 CPU (Intel Core 5 120U)
YOLO11n summary (fused): 101 layers, 2,582,347 parameters, 0 gradients, 6.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.0s/it 3.1s1.9s
                   all         40         43      0.945      0.907      0.951      0.732
Speed: 0.3ms preprocess, 32.8ms inference, 0.0ms loss, 7.0ms postprocess per image
Results saved to /workspace/runs/tune-ep10
MLflow: results logged to http://mlflow:5000
MLflow: disable with 'yolo settings mlflow=False'
MLflow: mlflow run still alive, remember to close it using mlflow.end_run()
🏃 View run cpu-ep10-416px at: http://mlflow:5000/#/experiments/7/runs/62fe34c7d0284adb83902a508fba6dde
🧪 View experiment at: http://mlflow:5000/#/experiments/7
[1/3] done in 442s

============================================================
[2/3] cpu-ep20-416px  {'epochs': 20, 'name': 'tune-ep20'}
============================================================
Ultralytics 8.4.116 🚀 Python-3.12.13 torch-2.13.0+cu130 CPU (Intel Core 5 120U)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/workspace/configs/data.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=416, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=tune-ep20, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/workspace/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/workspace/runs/tune-ep20, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    430867  ultralytics.nn.modules.head.Detect           [1, 16, None, [64, 128, 256]]
YOLO11n summary: 182 layers, 2,590,035 parameters, 2,590,019 gradients, 6.5 GFLOPs

Transferred 448/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
WARNING ⚠️ train: Slow image access detected (ping: 3.9±0.6 ms, read: 34.3±19.7 MB/s, size: 410.1 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning /workspace/data/processed/train/labels.cache... 160 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 160/160 67.1Mit/s 0.0s
WARNING ⚠️ val: Slow image access detected (ping: 3.4±0.8 ms, read: 49.6±38.3 MB/s, size: 929.1 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /workspace/data/processed/val/labels.cache... 40 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 40/40 28.0Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to /workspace/runs/tune-ep20/labels.jpg...
MLflow: logging run_id(da96e52ecad64f12a6eed71cef99326a) to http://mlflow:5000
MLflow: disable with 'yolo settings mlflow=False'
Image sizes 416 train, 416 val
Using 0 dataloader workers
Logging results to /workspace/runs/tune-ep20
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20         0G      1.139      3.191      1.067         11        416: 100% ━━━━━━━━━━━━ 20/20 1.8s/it 35.1s1.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2it/s 2.6s1.8s
                   all         40         43    0.00309       0.86      0.298      0.149

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20         0G       1.26      1.749      1.026         17        416: 100% ━━━━━━━━━━━━ 20/20 1.4s/it 28.6s1.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3s/it 4.0s2.8s
                   all         40         43      0.495     0.0698      0.119     0.0349

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20         0G      1.266      1.614      1.034         14        416: 100% ━━━━━━━━━━━━ 20/20 1.5s/it 30.6s1.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2it/s 2.5s1.8s
                   all         40         43    0.00242      0.674    0.00724    0.00277

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20         0G      1.229      1.529      1.052          8        416: 100% ━━━━━━━━━━━━ 20/20 1.6s/it 31.8s1.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2it/s 2.5s1.8s
                   all         40         43    0.00358          1      0.497      0.316

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20         0G        1.2      1.521      1.032          9        416: 100% ━━━━━━━━━━━━ 20/20 1.5s/it 30.0s1.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.6s1.7s
                   all         40         43      0.827      0.335       0.62      0.402

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20         0G      1.174      1.399     0.9974         12        416: 100% ━━━━━━━━━━━━ 20/20 1.5s/it 29.6s1.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.6s1.8s
                   all         40         43      0.871      0.788       0.87      0.556

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20         0G      1.101      1.299     0.9882         13        416: 100% ━━━━━━━━━━━━ 20/20 1.4s/it 28.8s1.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.7s1.8s
                   all         40         43      0.779      0.698      0.761      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20         0G      1.075      1.265      1.009         12        416: 100% ━━━━━━━━━━━━ 20/20 1.9s/it 38.6s2.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2s/it 3.7s2.5s
                   all         40         43       0.97      0.761      0.912      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/20         0G      1.089      1.161     0.9877         14        416: 100% ━━━━━━━━━━━━ 20/20 1.4s/it 28.4s1.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2it/s 2.5s1.7s
                   all         40         43       0.95      0.878      0.945      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/20         0G      1.092      1.136     0.9782         20        416: 100% ━━━━━━━━━━━━ 20/20 1.4s/it 27.7s1.9ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2it/s 2.4s1.7s
                   all         40         43      0.927      0.884      0.952      0.645
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/20         0G     0.9996      1.329      0.992          8        416: 100% ━━━━━━━━━━━━ 20/20 1.5s/it 29.5s1.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1s/it 3.3s2.1s
                   all         40         43      0.985      0.814      0.933      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/20         0G     0.9323      1.203     0.9435          8        416: 100% ━━━━━━━━━━━━ 20/20 1.9s/it 38.1s1.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.0s/it 3.1s2.0s
                   all         40         43       0.64      0.767      0.735        0.5

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/20         0G     0.8708      1.126     0.9086          8        416: 100% ━━━━━━━━━━━━ 20/20 1.3s/it 26.4s1.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.2it/s 2.5s1.7s
                   all         40         43      0.891      0.759      0.874      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/20         0G     0.8649      1.133     0.9224          8        416: 100% ━━━━━━━━━━━━ 20/20 1.6s/it 31.7s1.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1s/it 3.2s2.2s
                   all         40         43      0.968      0.791      0.932      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/20         0G     0.8855      1.063     0.9116          8        416: 100% ━━━━━━━━━━━━ 20/20 1.7s/it 33.5s1.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1s/it 3.3s2.4s
                   all         40         43      0.996      0.767      0.904      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/20         0G     0.8556      1.057     0.9329         10        416: 100% ━━━━━━━━━━━━ 20/20 1.8s/it 35.2s1.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.0s/it 6.1s2.1s
                   all         40         43      0.992      0.837      0.947      0.699

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/20         0G     0.7987     0.9777     0.8967          8        416: 100% ━━━━━━━━━━━━ 20/20 1.2s/it 23.1s1.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.8s1.9s
                   all         40         43          1      0.831      0.938      0.713

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/20         0G     0.7626     0.9307     0.8947          8        416: 100% ━━━━━━━━━━━━ 20/20 1.2s/it 24.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.3it/s 2.2s1.6s
                   all         40         43      0.941      0.907      0.969      0.749

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/20         0G     0.7959     0.9204      0.892          8        416: 100% ━━━━━━━━━━━━ 20/20 1.3s/it 26.1s1.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.7s1.8s
                   all         40         43      0.974      0.882      0.968      0.755

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/20         0G     0.8144     0.9778      0.867          8        416: 100% ━━━━━━━━━━━━ 20/20 1.7s/it 33.2s1.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.8s2.0s

## List experiment runs

List emperiment runs for comparison.

In [5]:
from src.tracking import compare_runs

table = compare_runs(EXPERIMENT)
table

,mlflow.runName,epochs,imgsz,data.train_images,metrics/mAP50B,metrics/mAP50-95B,metrics/precisionB,metrics/recallB
0,cpu-ep30-416px,30,416,160,0.974962,0.764988,1.000000,0.906955
1,cpu-ep20-416px,20,416,160,0.970052,0.756008,0.956956,0.906977
2,cpu-ep10-416px,10,416,160,0.951314,0.732104,0.944948,0.906977

visualize historical metrics

In [6]:
import matplotlib.pyplot as plt

# get historical run metrics
client = mlflow.tracking.MlflowClient()
experiment = mlflow.get_experiment_by_name(EXPERIMENT)
runs = mlflow.search_runs(experiment_ids=[experiment.experiment_id])

fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
for _, row in runs.iterrows():
    label = row["tags.mlflow.runName"]
    for ax, metric in zip(axes, ("metrics/mAP50B", "metrics/mAP50-95B")):
        history = client.get_metric_history(row["run_id"], metric)
        if history:
            ax.plot([p.step for p in history], [
                    p.value for p in history], marker="o", ms=3, label=label)

for ax, metric in zip(axes, ("mAP50", "mAP50-95")):
    ax.set_xlabel("epoch")
    ax.set_ylabel(metric)
    ax.set_title(metric)
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8)

plt.tight_layout()
plt.show()

In [7]:
# Cost against benefit -- more epochs always helps a little, so the question is
# whether the gain justifies the minutes.
cols = ["tags.mlflow.runName", "params.epochs", "metrics.metrics/mAP50-95B", "metrics.elapsed_seconds"]
cost = runs[[c for c in cols if c in runs.columns]].copy()
cost.columns = [c.split(".", 1)[-1] for c in cost.columns]
cost = cost.sort_values("epochs", key=lambda s: s.astype(int))
cost["min_per_0.01_mAP"] = (
    cost["elapsed_seconds"] / 60 / (cost["metrics/mAP50-95B"] * 100)
).round(2)
cost

   mlflow.runName epochs  metrics/mAP50-95B  elapsed_seconds  min_per_0.01_mAP
2  cpu-ep10-416px     10           0.732104       441.633076              0.10
1  cpu-ep20-416px     20           0.756008       701.681663              0.15
0  cpu-ep30-416px     30           0.764988      1053.732114              0.23

Browse the runs at http://127.0.0.1:5000.